### ISSUE TITLE
Update and combine setup scripts

### ISSUE THREAD

**Issue by Phosphenius** [Phosphenius/MyMoneyStats#11]
Currently the setup script consists of 2 separate scripts. One in Bash and the other in Python. Merge both into a single Python script which does all the work and has a different name than `setup.py` (reserved for packages/installers, use something like `setup_app.py`). Also make the script ask the user if they want to create an empty database or one populated with sample data.

**Comment by theovasi** [comment]
I'll work on this.

**Comment by theovasi** [comment]
Done #12  :simple_smile:
